import { join } from "node:path";
import { okAsync, type ResultAsync } from "neverthrow";
import {
  CODEX_PLUGIN_RELATIVE_PATH,
  WEAVE_CODEX_PLUGIN_NAME,
} from "./constants.js";
import type { CodexFileSystem, CodexFileSystemError } from "./filesystem.js";
import {
  renderAppManifest,
  renderHookManifest,
  renderMarketplace,
  renderMcpConfig,
  renderPluginManifest,
  renderSmokeApp,
  renderSmokeHookScript,
  renderSmokeMcpScript,
  renderWeaveSkill,
  renderWeaveSkillOpenAiMetadata,
} from "./render-plugin.js";

export type CodexPluginPackageResult = {
  readonly packageRoot: string;
  readonly writtenPaths: readonly string[];
};

export type CodexPluginPackageError = {
  readonly type: "CodexFileSystemError";
  readonly error: CodexFileSystemError;
};

export function packageCodexPluginArtifact(input: {
  readonly fs: CodexFileSystem;
  readonly outputRoot: string;
}): ResultAsync<CodexPluginPackageResult, CodexPluginPackageError> {
  const packageRoot = input.fs.resolvePath(
    join(input.outputRoot, WEAVE_CODEX_PLUGIN_NAME),
  );
  const files = [
    {
      path: join(packageRoot, ".codex-plugin/plugin.json"),
      content: renderPluginManifest(),
    },
    { path: join(packageRoot, "hooks.json"), content: renderHookManifest() },
    { path: join(packageRoot, ".mcp.json"), content: renderMcpConfig() },
    { path: join(packageRoot, ".app.json"), content: renderAppManifest() },
    {
      path: join(packageRoot, "skills/weave/SKILL.md"),
      content: renderWeaveSkill(),
    },
    {
      path: join(packageRoot, "skills/weave/agents/openai.yaml"),
      content: renderWeaveSkillOpenAiMetadata(),
    },
    {
      path: join(packageRoot, "hooks/weave-smoke-hook.ts"),
      content: renderSmokeHookScript(),
    },
    {
      path: join(packageRoot, "mcp/weave-smoke-mcp.ts"),
      content: renderSmokeMcpScript(),
    },
    {
      path: join(packageRoot, "apps/weave-smoke-app.json"),
      content: renderSmokeApp(),
    },
    {
      path: join(packageRoot, ".agents/plugins/marketplace.json"),
      content: renderMarketplace(undefined, {
        pluginSourcePath: `./${CODEX_PLUGIN_RELATIVE_PATH}`,
      }),
    },
    {
      path: join(packageRoot, "README.md"),
      content: [
        "# Weave Codex Plugin",
        "",
        "Publishable artifact generated by @weave/adapter-codex.",
        "Install through a Codex marketplace entry that points at this plugin root.",
        "",
      ].join("\n"),
    },
  ];

  let chain = okAsync<string[], CodexFileSystemError>([]);
  for (const file of files) {
    chain = chain.andThen((writtenPaths) =>
      input.fs
        .writeText(file.path, file.content)
        .map(() => [...writtenPaths, file.path]),
    );
  }

  return chain
    .map((writtenPaths) => ({ packageRoot, writtenPaths }))
    .mapErr(
      (error): CodexPluginPackageError => ({
        type: "CodexFileSystemError",
        error,
      }),
    );
}
